groups:
  - name: example_alerts
    rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total{job="node_exporter",mode="idle"} < 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage has been above 80% for more than 5 minutes on instance {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: node_memory_MemAvailable_bytes{job="node_exporter"} / node_memory_MemTotal_bytes{job="node_exporter"} < 0.2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Memory usage detected on {{ $labels.instance }}"
          description: "Memory usage has been above 80% for more than 5 minutes on instance {{ $labels.instance }}."
          
      - alert: ContainerMemoryUsage
        expr: sum(container_memory_usage_bytes{id=~"/docker/.*"}) by (container_label_io_kubernetes_pod_name) / sum(container_spec_memory_limit_bytes{id=~"/docker/.*"}) by (container_label_io_kubernetes_pod_name) > 0.8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Memory usage detected for container {{ $labels.container_label_io_kubernetes_pod_name }}"
          description: "Container {{ $labels.container_label_io_kubernetes_pod_name }} is using more than 80% of its allocated memory for more than 5 minutes."

      - alert: ContainerCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{id=~"/docker/.*"}[5m])) by (container_label_io_kubernetes_pod_name) / sum(machine_cpu_cores) > 0.8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected for container {{ $labels.container_label_io_kubernetes_pod_name }}"
          description: "Container {{ $labels.container_label_io_kubernetes_pod_name }} is using more than 80% of its allocated CPU for more than 5 minutes."
