global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8088']

  - job_name: 'my_application'
    static_configs:
      - targets: ['localhost:80']  # Adjust this to your application's metrics endpoint

    
