global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['52.90.147.63:8080']
    metrics_path: '/prometheus'

  - job_name: 'nginx'
    static_configs:
      - targets: ['52.90.147.63:80']
    metrics_path: '/status'

    
